import random
import sys

print("""DBテスト範囲問題集。最大259問。

""")

Qnum = int(input("問題数?: "))
if Qnum > 259:
 sys.exit()
if Qnum <= 0:
 sys.exit()

num = [i for i in range(259)]
J = ["専門家の助言を受けることを勧めるよ。", 
"彼女が返事をする間もなく、彼は電話を切った。", 
"彼は私の英作文の謝りを訂正した。",
"ヘレンは販売部長の仕事を引き受けた。",
"その政治家たちは、増税問題を討論した。",
"私たちは大雨にもかかわらず外出した。",
"その教授の講義は、私の理解を越えていた。",
"クジラは波の下に姿を消した。",
"大学に通う事のほかに、彼女は週15時間働いている。",
"それは世界のいたるところに事務所を構える巨大な組織だ。",
"ボイド先生はお休みです。したがって今日は英語の授業はありません。",
"深刻な病気ではないが、とにかく医者に診てもらったほうがいい。",
"大きな声でもう一度言っていただけませんか。",
"東京での生活費はとても高い。",
"近ごろはコンピュータの価格がとても安い。",
"彼女は高価なドレスを着ていた。",
"父は安い靴を1足買った。",
"この町は高齢者の人口が多い。",
"先月の私の出費は少なかった。",
"その木は少なくとも樹齢700年と見積もられている。",
"降雨量は3か月にわたって測定された。",
"私たちのクラスは5つのグループに分けられた。",
"この列の全ての数字を足してください。",
"私は英語に加えて、フランス語も勉強しなければならない。",
"失業者の数は1万人以上に達する。",
"多額のお金がその計画に投入された。",
"彼は100mを11秒以内で走ることができる。",
"彼女はもっとも有能な生徒の1人だ。",
"その会社はさらに大きな注文を取り扱うことができる。",
"彼は100mを11秒以内で走ることが可能だ。",
"彼はできるだけ速く逃走した。",
"新しい仕事に対する彼の態度は、とても前向きのようだった。",
"その問題は両者に公平なやり方で解決された。",
"彼女には怒ったときに早口で話すくせがある。",
"私は3時に教授と会う約束がある。",
"子どもの安全に対する関心が高まっている。",
"彼は政治情勢に興味がない。",
"変革の必要性について明らかな意見の一致があった。",
"政府は次の選挙の日付を公表した。",
"母は心を込めて訪問客を迎えた。",
"トムの母親は、トムが勉強しないことで彼をしかった。",
"床の上のネズミを見て、彼女は悲鳴を上げた。",
"私は電車でナンシーと口論した。",
"さあ、落ち着いて、深く呼吸しなさい。",
"フランキーは窓の外をじっと見つめ、深くため息をついた。",
"大学生がスマートフォンを持つのが標準的になった。",
"彼は素朴で平凡な生活を送っている。",
"この地域の平均的な降水量はどのくらいですか。",
"何か定期的な運動をしていますか。",
"これらのコインは珍しい。",
"大半の学生は研究対象に、ある特定の分野を選択する。",
"その通貨の相対的な価値は高い。",
"おじは自費で自伝を出版するつもりだ。",
"この本はこれまでに5万部印刷された。",
"そのインタビューはヨーロッパ中で生放送された。",
"その音楽家は優れた絵画も何枚か創作した。",
"この車は家族向けに設計されている。",
"その不祥事はメディアで広く報道された。",
"彼女は殺人で有罪の判決を受けた。",
"ビルは飲酒運転で逮捕された。",
"私は、警察官がそのスリの腕をつかむのを見た。",
"その湖は木々に囲まれている。",
"植民地時代には、先住部族は入植者たちに虐げられた。",
"子どもたちがこの湖で泳ぐのは危険だ。",
"あなたが彼に助けを求めてもむだだ。",
"私たちが君たちのチームを破るのは不可能だ。",
"あなたは車でそこへ行くほうが、より便利だ。",
"彼は手術を受けることが必要になるかもしれない。",
"あなたは、明日の会議のおもな議題を知っていますか。",
"私たちは彼の指揮なしでその計画を実行することはできない。",
"パイロットのストライキの結果として、全便が欠航せざるを得なくなった。",
"この点についての結論を出すのはまだ早すぎる。",
"私はその会議に出席する機会を逃した。",
"彼は、その新しい委員会の主要なメンバーの1人だ。",
"それらの単語はまったく正反対の意味だ。",
"あの政党はその政策に反対している。", 
"最近の世論調査で住民の80%が知事を支持していることがわかった。",
"彼女は彼の正直さを尊敬する。",
"その問題に関しては、私は何も情報を持っていない。",
"私は彼が成し遂げたことに感心している。",
"私の弟はこの長編小説のよさがわかるには若すぎる。",
"十分な議論を経て委員会は決断を下した。",
"企画委員会は15人のメンバーで構成されている。",
"彼は貿易問題についての声明を出した。",
"彼の戦略はとても巧みだったので、彼はチェスの勝負に容易に勝った。",
"失敗から何か大切なものを得ることができる。",
"私たちのウェブサイトから、さらなる詳細を手に入れられます。",
"試合の残り1分で彼が得点したとき、観衆は歓声をあげた。",
"ケビンには新しいことに挑戦する意欲がない。",
"最近、喫煙者の数が減ってきている。",
"私たちはバスルームのタイルを取りかえた。",
"古い壁紙を取り去って、壁のくぼみを埋めなさい。",
"私たちは少し違った方法を採用することに決めた。",
"あなたは何をじっと見ているのですか。",
"彼らはジャングルでインカ人の遺跡を発見した。",
"環境保護団体がその森林を保護しようと努めている。",
"その地域は徹底的に捜索された。",
"君は制服を着ていたから、私は君がだれだかわからなかった。",
"その本には育児に関するよいアドバイスがたくさん載っている。",
"機内には手荷物をいくつ持ち込めますか。",
"私は家に新しい家具をいくつか買いたいと思っている。",
"私は君に伝えたい情報が2つある。",
"私たちは省力型の機械装置に頼るようになってきた。",
"昨日はあまりニュースがなかった。",
"私は湾の上を飛ぶカモメの群れを見た。",
"車から、野原にいる水牛の群れが見えた。",
"イルカはしばしば海洋の魚群とともに移動する。",
"その暑い午後のあいだ犬は日陰に座っていた。",
"王子の像は地面に長い影を落としていた。",
"あなたはすぐに歯科医にみてもらうべきだ。",
"私は祖母の命を救った外科医に感謝した。",
"すみません、この飛行機にお医者様はいらっしゃいますか。",
"私は今週の土曜日までに夏休みの宿題を終えなければならない。",
"私の母は、父が家事を十分にしていないとよく不平を言っている。",
"シェイクスピアの演劇や詩は英語では最高の作品と考えられている。",
"私は新幹線に乗っているあいだ美しい景色を見るのが好きだ。",
"万年筆で書くことは、実はとても楽しいことだ。",
"日本経済には回復のきざしがいくつかある。",
"このカメラの価格は税込でいくらですか。",
"象牙の貿易は1990年以降、禁止されている。",
"中国では重工業が急速に発展している。",
"その会社は昨年、30万ドルの損失があった。",
"今年、消費者はより多くお金を使っている。",
"ワインの関税が上がった。",
"私は銀行で私の残高を確認するつもりだ。",
"私たちはすべてのお客様にこれ以上はない満足を保証する。",
"8人の新たなメンバーが間もなく私たちのクラブに加わる予定だ。",
"400人以上の子供たちが公園の清掃に参加した。",
"その講座は研修会社によって準備された。",
"犯罪を撲滅するために人々は警察と協力しなければならない。",
"彼は混乱していて自分の意思を伝えることができなかった。",
"音楽家として生計を立てるのは難しいかもしれない。",
"彼らは車椅子に乗った男性に道を譲った。",
"その2人の友だちは船の方へやっとのことで進んだ。",
"彼らはサーフボードを持って海岸の方へ向かった。",
"あなたが来てくれてうれしいです。気楽にしてください。",
"太郎は新しい学校で多くの学生と友達になった。",
"ほとんどの専門家は高価なダイヤモンドを安物と見分けることができる。",
"母親は、言われたようにしないので娘をしかった。",
"何か質問があれば、遠慮なく聞きなさい。",
"食卓でみんな黙っていたので、私は落ち着かない感じがした。",
"彼女は授業に20分遅れて現れた。",
"生徒たちは毎週1回、ワークブックを提出する。",
"私は12歳のときに自転車に乗ることができるようになった。",
"私はこの問題をじっくり考える必要がある.",
"雨が降るときはいつも、屋根が雨漏りする。",
"マラソン走者たちが次々とゴールした。",
"教授は何時間も連続して論文を書いた。",
"雨の日にはたいていバスが遅れてくる。",
"午後はずっと雨が降ったり止んだりした。",
"私は学校で彼女をときどき見かけるだけだ。",
"きっぱりと、この問題に決着をつけよう。",
"長い目で見れば、私たちのした苦労は無駄にはならないだろう。",
"部屋に入るとすぐに、私は何かおかしいと気づいた。",
"家に着いたらすぐに、私に電話をしてほしい。",
"彼が座ると同時に、チャイムが鳴った。",
"私が事務所に到着すると同時に、電話が鳴った。",
"私は君の伝言をもらうとすぐに来た。",
"彼も奥さんもその映画を楽しんだ。",
"彼の言うことでなく、彼の言い方が嫌なのです。",
"シェイクスピアは作家であるだけでなく、役者でもあった。",
"ライスかパスタのどちらかをお召し上がりいただけます。",
"その装置は有益でも安全でもない。",
"彼女に聞こえないように、私は声を落とした。",
"新たな治療法が開発されるために、その研究が必要だ。",
"彼女を動揺させないように、私は事故のことを教えなかった。",
"雨が降るといけないから、傘を持っていきなさい。",
"その政治家はそのスキャンダルとは関係がなかった。",
"もし契約が取れなかったなら、私たちの懸命な仕事はすべてむだになってしまうだろう。",
"食べるものがサラダしかなかった。",
"テレビの調子が悪い。",
"私は背中に痛みがあったが、そのときはそれを何とも思わなかった。",
"その箱は私が持ち上げるには重すぎた。",
"その部屋は3台のベッドを置くのに十分な広さがある。",
"私は不注意にも鍵を中に入れたまま車をロックしてしまった。",
"彼は演技を上達させるために、毎日トレーニングした。",
"誰の感情も害さないように、私が訪ねた本当の理由は言わなかった。",
"混雑する時間帯を避けるために、私たちは早く出発した。",
"その小さな男の子は捕まらないように逃げ出した。",
"今日の午後、私は社長に会うことになっている。",
"その企画を成功させるつもりなら、君には私たちの援助が必要だ。",
"全職員は制服を着用しなければならない。",
"空には星1つ見ることができなかった。",
"私はどこに鍵を置いたのかをどうしても思い出せない。",
"どんな状況でも彼は気持ちを変えないだろう。",
"彼はめったに時間通りにこない。",
"今のところ新車なんて論外だ。",
"できることなら、私は病気にはなりたくない。",
"一般的に言えば、日本人は礼儀正しい国民だ。",
"誕生日といえば、君のはいつですか。",
"彼女の服から判断すると、彼女はかなりの金持ちだろう。",
"急な通知であったことを考慮すると、彼はとてもいい仕事をした。",
"天気が良ければ、私は今日の午後ゴルフをするつもりだ。",
"彼女は腕を組んで私たちの正面に立っていた。",
"その列車に乗りたいのなら、急ぎなさい。",
"健康でいるために君は何かスポーツでも始めるべきだ。",
"あなたはここに長くいる必要がない。",
"次に何が起きるのかは知りようがない。",
"今日、私は歌いたい気がする。",
"映画を見にいくのはどうですか。",
"私は家族に再会するのを楽しみに待っている。",
"君は都会で運転するのに慣れている。",
"私の妻は私が40代で転職するのに反対した。",
"釣りをするということになると、私の兄[弟]より上手な人はいない。",
"このシャツは洗濯される必要がある。",
"インターネットが優れた情報源だということは言うまでもない。",
"彼は中国との貿易で多くの利益を得た。",
"新しいクレジットカードは、お客様にとって大きな利益になるだろう。",
"産業の目的は富を生み出すことだ。",
"その彫刻の価値は50万ドルと見積もられた。",
"政府は外国資本を導入することに熱心だ。",
"共同経営者はそれぞれ、利益の分け前を受け取る。",
"核兵器は廃止されるべきだ。",
"彼の息子たちは2人とも軍隊にいるそうだ。",
"彼らはあの店でさまざまな商品を買った。",
"ほとんどの人にとって、車は依然として主要な交通手段だ。",
"皆、学年の初めは上機嫌だった。",
"彼は平均的な身長と体重だ。",
"私たちはベルリン中心部の広い大通りを歩いた。",
"あの巨大な山の名前は何ですか。",
"私がなくしたイヤリングはとても小さかった。",
"彼らはたった1点差で試合に勝った。",
"その魚は5メートルの深さに生息している。",
"航空運賃がおよそ20%急上昇した。",
"その講座の(受講)料金は2500円です。",
"このサービスには追加の料金がかかります。",
"お勘定をお願いできますか。",
"この動物園では65歳を超えている人は入場料を払わなくてもよい。",
"その値段に税金は含まれていませんので、ご注意ください。",
"前回の選挙では誰に投票したのですか。",
"彼は大工で生計を立てている。",
"その会社は来年、技師を何人か雇う予定だ。",
"1週間以内にこの家を完成させるには、あと何人か大工を雇う必要がある。",
"カナダは日本に小麦を輸出している。",
"日本は世界中から原料と燃料を輸入している。",
"強い日差しから肌を保護するべきだ。",
"大統領はテレビで演説をした。",
"妻の収入は私の収入より多い。",
"彼の給与でどうしてあんな車が買えるのだろうか。",
"私たちの先月の賃金がまだ支払われていない。",
"あの会社の給料はかなりよいと言われている。",
"事故のために電車が50分遅れた。",
"あなたの邪魔をして申し訳ないですが、私たちはあなたの助言が必要です。",
"エレンが読書をしているときは、彼女の邪魔をしないでください。",
"制限速度を無視してはいけない。",
"私は騙されていたことにようやく気づいた。",
"娘は私に子猫をねだっている。",
"私は午後3時に大切な依頼人と会う約束がある。",
"観客は拍手喝采し始めた。",
"その試合は5万人以上の観客を集めた。",
"運転手にも乗客たちにもけがはなかった。",
"彼は当店の常連客の1人だ。",
"このホテルは宿泊客をよく気遣ってくれる。",
"カーテンが台所と居間を分けている。",
"青函トンネルは青森と北海道を繋いでいる。",
"パスワードは少なくとも5文字から構成されていなければならない。",
"自分を他人と比較する必要はない。",
"特別な夜のためにこのワインを取っておきたい。",
"私は今日、するべき仕事がたくさんある。"]

E_sentence = ["I (      ) that you get some professional advice.",
"He hung up before she had a chance to (      ).",
"He (      ) some errors in my English composition.",
"Helen (      ) the job of sales manager.",
"The politicians (      ) the question of raising taxes.",
"We went out (      ) the heavy rain.",
"The professor's lecture was (      ) my understanding.",
"The whale disappeared (      ) the waves.",
"(      ) going to college, she works fifteen hours a week.",
"It is a large organization with offices (      ) the world.",
"Ms. Boyd is absent and (      ) we have no English class today.",
"It's not a serious illness, but you should see a doctor (      ).",
"Would you say it (      ) again in a loud voice?",
"The cost of living in Tokyo is very (      ).",
"Computer prices are very (      ) nowadays.",
"She wore an (      ) dress.",
"My father bought a pair of (      ) shoes.",
"This town has a (      ) population of older people.",
"My expenses were (      ) last month.",
"The tree is (      ) to be at least 700 years.",
"The rainfall was (      ) over a three-month period.",
"Our class was (      ) into five groups.",
"Please (      ) all the numbers on this line.",
"I have to study French in (      ) to English.",
"The number of unemployed people (      ) to more than 10000.",
"A large (      ) of money was put into the project.",
"He is (      ) to run 100 meters within eleven seconds.",
"She is one of our most (      ) students.",
"The company is (      ) of handling larger orders.",
"It is (      ) for him to run 100 meters within eleven seconds.",
"He ran away as fast as (      ).",
"His (      ) toward his new job seemed to be very positive.",
"The issue was resolved in a (      ) that was fair to both sides.",
"She has a (      ) of speaking quickly when she is angry.",
"I have an (      ) with the professor at three o'clock.",
"(      ) is growing for the children's safety.",
"He is not interested in political (      ).",
"There was a clear (      ) on the need for change.",
"The government has (      ) the date of the next election.",
"My mother (      ) the visitors warmly.",
"Tom's mother (      ) him for not studying.",
"She (      ) when she saw a mouse on the floor.",
"I had a (      ) with Nancy on the train.",
"Now relax and (      ) deeply.",
"Frankie stared out of the window and (      ) deeply.",
"It has become (      ) for college students to have a smartphone.",
"He leads a simple and (      ) life.",
"What is the (      ) rainfall in this area?",
"Do you do any (      ) exercise?",
"These coins are (      ).",
"Most students choose a (      ) area for their research.",
"The (      ) value of that currency is high.",
"My uncle will (      ) his autobiography at his own expense.",
"50000 copies of this book have been (      ) so far.",
"The interview was (      ) live across Europe.",
"The musician also (      ) some fine paintings.",
"This car is (      ) for families.",
"The scandal was widely reported in the (      ).",
"She was found guilty of (      ).",
"Bill was (      ) for drunk driving.",
"I saw a policeman (      ) the pickpocket by the arm.",
"The lake is (      ) by trees.",
"In colonial times, native tribes were (      ) by the settlers.",
"It is (      ) for children to swim in this lake.",
"It is (      ) for you to ask him for help.",
"It's (      ) for us to beat your team.",
"It is more (      ) for you to go there by car.",
"It may be (      ) for him to have an operation.",
"Do you know the main (      ) of tomorrow's meeting?",
"We can't carry out the plan without his (      ).",
"As a (      ) of the pilots' strike, all flights have had to be canceled.",
"It is still too early to reach a (      ) on this point.",
"I missed an (      ) to attend the meeting.",
"He is one of the (      ) members of the new committee.",
"Those words have completely (      ) meanings.",
"That political party is in (      ) to the policy.",
"A recent (      ) found that 80 percent of the citizens support the governor.",
"She (      ) him for his honesty.",
"With (      ) to that matter, I don't have any information.",
"I (      ) him for what he's achieved.",
"My brother is too young to (      ) this long novel.",
"The (      ) made a decision after much discussion.",
"The planning (      ) is made up of fifteen members.",
"He made a (      ) about the trade problem.",
"His (      ) was so clever that he easily won the chess game.",
"You can (      ) something important from your failure.",
"Further details can be (      ) from our website.",
"The crowd cheered when he (      ) in the final minute of the game.",
"Kevin (      ) a desire to try new things.",
"The number of smokers has been (      ) recently.",
"We (      ) the tiles in the bathroom.",
"(      ) the old wallpaper and fill any holes in the walls.",
"We've decided to (      ) a slightly different approach.",
"What are you (      ) at?",
"They (      ) Inca ruins in the jungle.",
"Environmental groups are (      ) to protect the forests.",
"The area was thoroughly (      ).",
"I didn't (      ) you in your uniform.",
"There's lots of good (      ) in the book on child care.",
"How many pieces of (      ) can I carry on the airplane?",
"I want to get some new (      ) for my house.",
"I have two pieces of (      ) to pass on to you.",
"We have come to depend on labor-saving (      ).",
"There wasn't much (      ) yesterday.",
"I saw a (      ) of seagulls flying over the bay.",
"From the car we saw a (      ) of buffalo on the field.",
"Dolphins often travel with (      ) of fish in the ocean.",
"The dog sat in the (      ) during that hot afternoon.",
"The statue of the prince cast a long (      ) on the ground.",
"You should go to the (      ) soon.",
"I thanked the (      ) who saved my grandmother's life.",
"Excuse me, do we have a (      ) on board this plane?",
"I have to finish my summer (      ) by this Saturday.",
"My mom often complains that my dad doesn't do enough of the (      ).",
"The plays and (      ) of Shakespeare are considered to be the greatest works in English.",
"I like to look at the beautiful (      ) while riding on the Shinkansen.",
"Writing with a fountain pen is actually a lot of (      ).",
"There are some signs of recovery in the Japanese (      ).",
"What's the (      ) of this camera, including tax?",
"(      ) in ivory has been banned since 1990.",
"Heavy (      ) are rapidly developing in China.",
"The company had a (      ) of 300,000 dollars last year.",
"(      ) are spending more this year.",
"The (      ) on wine has gone up.",
"I'm going to check my (      ) at the bank.",
"We (      ) complete satisfaction for all our clients.",
"Eight new members are expected to (      ) our club soon.",
"More than 400 children (      ) in a clean-up of the park.",
"The course was (      ) by a training company.",
"People must (      ) with the police to defeat crime.",
"He was confused and couldn't (      ) (      ) (      ).",
"It may be hard to (      ) (      ) (      ) as a musician.",
"They (      ) (      ) (      ) the man in the wheelchair.",
"The two friends (      ) (      ) (      ) toward the ship.",
"They (      ) (      ) the beach with their surfboards.",
"I'm glad you came. (      ) (      ) (      ) (      ), please.",
"Taro (      ) (      ) (      ) many students at his new school.",
"Most experts can (      ) an expensive diamond (      ) a cheap one.",
"The mother (      ) her daughter (      ) for not doing as she was told.",
"If you have any questions, (      ) (      ) (      ) ask.",
"Everybody was silent at the table and I (      ) (      ) (      ) (      ).",
"She (      ) (      ) twenty minutes late for class.",
"The students (      ) (      ) their exercise books once a week.",
"I (      ) (      ) ride a bicycle when I was 12.",
"I need to (      ) (      ) this matter.",
"The roof leaks (      ) (      ) it rains.",
"The marathon runners reached the finish line (      ) (      ) (      ).",
"The professor spent hours (      ) (      ) writing his paper.",
"(      ) (      ) (      ) (      ), the buses come late on rainy days.",
"It rained (      ) (      ) (      ) for the whole afternoon.",
"I only see her (      ) (      ) (      ) (      ) at school.",
"Let's settle this matter (      ) (      ) (      ) (      ).",
"All our hard work will be worth it (      ) (      ) (      ) (      ).",
"(      ) (      ) (      ) I walked into the room, I knew there was something wrong.",
"I want you to call me (      ) (      ) you get home.",
"(      ) (      ) had he sat down (      ) the bell rang.",
"I had (      ) arrived in the office (      ) the phone rang.",
"I came (      ) I got your message.",
"(      ) he (      ) this wife enjoyed the movie.",
"I dislike (      ) what he says (      ) the way he says it.",
"Shakespeare was (      ) (      ) a writer (      ) (      ) an also an actor.",
"You can have (      ) rice (      ) pasta.",
"The equipment is (      ) useful (      ) safe.",
"I lowered my voice (      ) (      ) she wouldn't hear.",
"The research is necessary (      ) (      ) (      ) new treatments can be developed.",
"I didn't tell her about the accident (      ) (      ) (      ) I might upset her.",
"Take an umbrella, (      ) (      ) it rains.",
"The politician (      ) (      ) (      ) (      ) (      ) the scandal.",
"If we don't get the contract, all our hard work will have been (      ) (      ).",
"There was (      ) (      ) salad to eat.",
"(      ) (      ) (      ) (      ) the TV.",
"I had a pain in my back but (      ) (      ) (      ) it at the time.",
"The box was (      ) heavy (      ) me (      ) lift.",
"The room is large (      ) (      ) put three beds in it.",
"I was (      ) careless (      ) (      ) lock the car with the key inside.",
"He trained every day (      ) (      ) (      ) improve this performance.",
"(      ) (      ) (      ) (      ) offend anyone, I did not tell them the real reason for my visit.",
"We left early (      ) (      ) (      ) avoid the busy period.",
"The little boy ran off (      ) (      ) (      ) (      ) be caught.",
"I (      ) (      ) meet the president this afternoon.",
"If you (      ) (      ) succeed in the project, you will need our help.",
"All staff members (      ) (      ) wear uniforms.",
"Not a star (      ) (      ) be seen in the sky.",
"I can't (      ) (      ) (      ) (      ) (      ) remember where I put my keys.",
"(      ) (      ) (      ) would he change his mind.",
"He (      ), (      ) (      ), arrives on time.",
"A new car is (      ) (      ) (      ) (      ) at the moment.",
"I don't want to become sick (      ) (      ) (      ) (      ) (      ).",
"(      ) (      ), the Japanese are a polite people.",
"(      ) (      ) birthdays, when's yours?",
"I would say she's pretty rich, (      ) (      ) her clothes.",
"(      ) the short notice, he did a very good job.",
"I'm playing golf this afternoon, (      ) (      ).",
"She stood in front of us (      ) (      ) (      ) (      ).",
"You (      ) (      ) hurry if you want to catch the train.",
"You (      ) (      ) take up some sport to stay in shape.",
"You (      ) (      ) stay long here.",
"(      ) (      ) (      ) knowing what will happen next.",
"I (      ) (      ) singing today.",
"(      ) (      ) going to see a movie?",
"I'm (      ) (      ) (      ) seeing my family again.",
"You (      ) (      ) (      ) driving in the city.",
"My wife (      ) (      ) my changing jobs in my forties.",
"(      ) (      ) (      ) (      ) fishing, no one is better than my brother.",
"This shirt (      ) washing.",
"(      ) (      ) (      ) (      ) (      ) the Internet is a good source of information.",
"He made a lot of (      ) from trading with China.",
"The new credit cards will be of great (      ) to our customers.",
"The purpose of industry is to create (      ).",
"The (      ) of the sculpture was estimated at 500,000 dollars.",
"The government is eager to attract foreign (      ).",
"Each partner gets a (      ) of the profits.",
"Nuclear (      ) should be abolished.",
"I heard both of his sons are in the armed (      ).",
"They bought a variety of (      ) at that store.",
"For most people, the car is still their main (      ) of transportation.",
"Everyone was in high (      ) at the beginning of the school year.",
"He is of average (      ) and weight.",
"We walked along the (      ) streets of central Berlin.",
"What's the name of that (      ) mountain?",
"The earnings I lost were (      ).",
"They won the game by a (      ) point.",
"The fish are found at a (      ) of five meters.",
"Air (      ) have shot up about 20 percent.",
"The (      ) for the course is 2500 yen.",
"There is an extra (      ) for this service.",
"Could we have the (      ), please?",
"People over sixty-five do not have to pay (      ) to this zoo.",
"Please note that the price does not include (      ).",
"Who did you (      ) for in the last election?",
"He (      ) his living as a carpenter.",
"The company will (      ) some engineers next year.",
"We must (      ) some more carpenters to finish this house within a week.",
"Canada (      ) wheat to Japan.",
"Japan (      ) raw materials and fuel from all over the world.",
"You should (      ) your skin from strong sunlight.",
"The President (      ) his speech on TV.",
"My wife's (      ) is higher than mine.",
"How can he afford a car like that on his (      )?",
"Our (      ) for last month still have not been paid.",
"The (      ) at that company is said to be quite good.",
"The train was (      ) for fifty minutes due to an accident.",
"I'm sorry to (      ) you, but we need your advice.",
"Please don't (      ) Ellen when she is reading.",
"You must not (      ) the speed limit.",
"I finally realized that I had been (      ).",
"My daughter has been (      ) me for a kitten.",
"I have an appointment with an important (      ) at 3:00 p.m.",
"The (      ) began clapping and cheering.",
"The game attracted over 50,000 (      ).",
"Neither the driver nor the (      ) were hurt.",
"He's one of our regular (      ).",
"This hotel takes good care of its (      ).",
"A curtain (      ) the kitchen from the living room.",
"The Seikan Tunnel (      ) Aomori with Hokkaido.",
"The password should (      ) of at least five characters.",
"You don't have to (      ) yourself to others.",
"I'd like to (      ) this wine for a special night.",
"I have a lot of (      ) to do today."]


E = ["recommend",
"reply",
"corrected",
"accepted",
"debated",
"despite",
"beyond",
"beneath",
"Besides",
"throughout",
"therefore",
"anyway",
"once",
"high",
"low",
"expensive",
"cheap",
"large",
"small",
"estimated",
"measured",
"divided",
"add",
"addition",
"amounts",
"amount",
"able",
"able",
"capable",
"possible",
"possible",
"attitude",
"manner",
"habit",
"appointment",
"Concern",
"affairs",
"consensus",
"announced",
"greeted",
"scolded",
"screamed",
"quarrel",
"breathe",
"sighed",
"normal",
"ordinary",
"average",
"regular",
"rare",
"particular",
"relative",
"publish",
"printed",
"broadcast",
"created",
"designed",
"media",
"murder",
"arrested",
"seize",
"surrounded",
"oppressed",
"dangerous",
"useless",
"impossible",
"convenient",
"necessary",
"topic",
"direction",
"result",
"conclusion",
"opportunity",
"principal",
"opposite",
"opposition",
"poll",
"respects",
"respect",
"admire",
"appreciate",
"board",
"committee",
"statement",
"strategy",
"gain",
"obtained",
"scored",
"lacks",
"decreasing",
"replaced",
"Remove",
"adopt",
"staring",
"discovered",
"seeking",
"searched",
"recognize",
"advice",
"baggage",
"furniture",
"information",
"machinery",
"news",
"flock",
"herd",
"schools",
"shade",
"shadow",
"dentist",
"surgeon",
"physician",
"homework",
"housework",
"poetry",
"scenery",
"fun",
"economy",
"price",
"Trade",
"industries",
"loss",
"Consumers",
"duty",
"balance",
"guarantee",
"join",
"participated",
"organized",
"unite",
"make himself understood",
"make a living",
"made way for",
"made their way",
"made for",
"Make yourself at home",
"made friends with",
"tell from",
"told off",
"feel free to",
"felt ill at ease",
"showed up",
"hand in",
"learned to",
"think over",
"every time",
"one after another",
"on end",
"More often than not",
"on and off",
"once in a while",
"once and for all",
"in the long run",
"As soon as",
"the moment",
"No sooner than",
"hardly when",
"directly",
"Both and",
"not but",
"not only but also",
"either or",
"neither nor",
"so that",
"in order that",
"for fear that",
"in case",
"had nothing to do with",
"for nothing",
"nothing but",
"Something is wrong with",
"thought nothing of",
"too for to",
"enough to",
"so as to",
"in order to",
"In order not to",
"so as to",
"so as not to",
"am to",
"are to",
"are to",
"was to",
"for the life of me",
"Under no circumstances",
"seldom if ever",
"out of the question",
"if I can help it",
"Generally speaking",
"Speaking of",
"judging from",
"Considering",
"weather permitting",
"with her arms folded",
"had better",
"ought to",
"need not",
"There is no",
"feel like",
"How about",
"looking forward to",
"are used to",
"objected to",
"When it comes to",
"needs",
"It goes without saying that",
"profit",
"benefit",
"wealth",
"value",
"capital",
"share",
"arms",
"forces",
"goods",
"means",
"spirits",
"height",
"broad",
"huge",
"tiny",
"single",
"depth",
"fares",
"fee",
"charge",
"bill",
"admission",
"tax",
"vote",
"earns",
"employ",
"hire",
"exports",
"imports",
"protect",
"delivered",
"income",
"salary",
"wages",
"pay",
"delayed",
"disturb",
"bother",
"ignore",
"tricked",
"begging",
"client",
"audience",
"spectators",
"passengers",
"customers",
"guests",
"separates",
"connects",
"consist",
"compare",
"reserve",
"work"]

wrong_list = []
score = 0

random.shuffle(num)

for i in range(Qnum):
 print(i + 1)
 print(J[num[i]])
 print(E_sentence[num[i]])
 ans = input()
 if ans == E[num[i]]:
  print("Correct.")
  score += 1
 else:
 	print("Wrong.")
 	print("Ans:", E[num[i]])
 	wrong_list.append(num[i])
 print()
 print()

wrong_list.sort()

print("RESULT:")
print(score, "/", Qnum)
print([E[i] for i in wrong_list])
if score == Qnum:
 print("Perfect!")
